# AoC Day 2 Challenge. First section is grabbing the input text for the day

In [1]:
# Common Imports
import pycurl as curl
from io import BytesIO
import pandas as pd
import numpy as np
import re
import os

In [2]:
# Get input as `input`
year = 2024
day = 2

with open('/home/alec/aoc_cookie.txt', 'r') as file:
    cookie = file.read() 

buffer = BytesIO()
c = curl.Curl()
c.setopt(curl.URL, f"https://adventofcode.com/{year}/day/{day}/input")
c.setopt(curl.COOKIE, f"session={cookie}")
c.setopt(curl.WRITEDATA, buffer)
c.perform()
c.close()

input = buffer.getvalue().decode('utf-8')

# Part 1

In [3]:
entries = input.splitlines()

In [13]:
safe_reports = 0

for entry in entries:
    # print(entry)
    arr = np.array([int(i) for i in entry.split()])
    arr_diff = np.diff(arr)
    # print(arr_diff)
    if np.sum(np.abs(arr_diff) < 1) or np.sum(np.abs(arr_diff) > 3):
        continue

    if np.sum(arr_diff < 0) == len(arr_diff) or np.sum(arr_diff > 0 ) == len(arr_diff):
        safe_reports += 1
        # print("SAFE")
    # print(len(arr_diff))
    # break

print(safe_reports)

45 47 48 51 54 56 54
[ 2  1  3  3  2 -2]
76 79 81 84 84
[3 2 3 0]
30 32 35 36 38 40 44
[2 3 1 2 2 4]
72 74 77 78 85
[2 3 1 7]
54 55 58 57 60
[ 1  3 -1  3]
61 64 67 66 68 67
[ 3  3 -1  2 -1]
5 7 6 9 12 14 16 16
[ 2 -1  3  3  2  2  0]
82 83 84 82 85 88 91 95
[ 1  1 -2  3  3  3  4]
38 40 43 46 49 47 53
[ 2  3  3  3 -2  6]
23 26 28 31 34 35 35 36
[3 2 3 3 1 0 1]
74 75 78 80 81 81 79
[ 1  3  2  1  0 -2]
11 13 16 17 18 18 20 20
[2 3 1 1 0 2 0]
20 21 22 23 23 27
[1 1 1 0 4]
63 64 64 65 68 71 73 79
[1 0 1 3 3 2 6]
44 47 49 53 55 56 58 59
[3 2 4 2 1 2 1]
81 82 84 87 88 92 89
[ 1  2  3  1  4 -3]
32 35 38 40 44 44
[3 3 2 4 0]
53 55 59 60 62 64 65 69
[2 4 1 2 2 1 4]
53 55 56 58 62 67
[2 1 2 4 5]
57 59 62 68 71 73 74 75
[2 3 6 3 2 1 1]
22 24 25 30 33 35 38 36
[ 2  1  5  3  2  3 -2]
15 17 20 25 28 30 32 32
[2 3 5 3 2 2 0]
83 85 88 94 98
[2 3 6 4]
74 77 78 80 87 92
[3 1 2 7 5]
57 55 58 61 63 64 65 67
[-2  3  3  2  1  1  2]
74 71 73 74 75 73
[-3  2  1  1 -2]
32 31 34 35 35
[-1  3  1  0]
35 32 34 36 38

1889772


# Part 2

In [34]:
safe_reports = 0
from copy import copy

def check(entry):
    arr = np.array(entry)
    arr_diff = np.diff(arr)
    # print(arr_diff)

    if np.sum(np.abs(arr_diff) < 1) or np.sum(np.abs(arr_diff) > 3):
        return False

    if np.sum(arr_diff < 0) == len(arr_diff) or np.sum(arr_diff > 0 ) == len(arr_diff):
        return True
    return False

total = 0
print(len(entries))
for entry in entries:
    print(entry)
    entry_arr = [int(i) for i in entry.split()]
    if check(entry_arr):
        total += 1
        continue
    entry_arr = [int(i) for i in entry.split()]
    print(len(entry_arr))
    for i in range(len(entry_arr)):
        new_entry = copy(entry_arr)
        new_entry.pop(i)
        print(f"{i} {new_entry}")
        if check(new_entry):
            total +=1
            break


        # print("SAFE")
    # print(len(arr_diff))
    # break

print(total)

1000
45 47 48 51 54 56 54
7
0 [47, 48, 51, 54, 56, 54]
1 [45, 48, 51, 54, 56, 54]
2 [45, 47, 51, 54, 56, 54]
3 [45, 47, 48, 54, 56, 54]
4 [45, 47, 48, 51, 56, 54]
5 [45, 47, 48, 51, 54, 54]
6 [45, 47, 48, 51, 54, 56]
76 79 81 84 84
5
0 [79, 81, 84, 84]
1 [76, 81, 84, 84]
2 [76, 79, 84, 84]
3 [76, 79, 81, 84]
30 32 35 36 38 40 44
7
0 [32, 35, 36, 38, 40, 44]
1 [30, 35, 36, 38, 40, 44]
2 [30, 32, 36, 38, 40, 44]
3 [30, 32, 35, 38, 40, 44]
4 [30, 32, 35, 36, 40, 44]
5 [30, 32, 35, 36, 38, 44]
6 [30, 32, 35, 36, 38, 40]
72 74 77 78 85
5
0 [74, 77, 78, 85]
1 [72, 77, 78, 85]
2 [72, 74, 78, 85]
3 [72, 74, 77, 85]
4 [72, 74, 77, 78]
54 55 58 57 60
5
0 [55, 58, 57, 60]
1 [54, 58, 57, 60]
2 [54, 55, 57, 60]
61 64 67 66 68 67
6
0 [64, 67, 66, 68, 67]
1 [61, 67, 66, 68, 67]
2 [61, 64, 66, 68, 67]
3 [61, 64, 67, 68, 67]
4 [61, 64, 67, 66, 67]
5 [61, 64, 67, 66, 68]
5 7 6 9 12 14 16 16
8
0 [7, 6, 9, 12, 14, 16, 16]
1 [5, 6, 9, 12, 14, 16, 16]
2 [5, 7, 9, 12, 14, 16, 16]
3 [5, 7, 6, 12, 14, 16, 16]
